name: Run R Pipeline

on:
  schedule:
    - cron: '0 12 * * *'   # Roda diariamente às 9h da manhã (horário BR)
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    container:
      image: rocker/tidyverse:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install additional packages
        run: |
          R -e 'install.packages(c("httr", "jsonlite", "DBI", "RPostgres"), dependencies = TRUE)'

      - name: Run R pipeline
        env:
          NEON_PW: ${{ secrets.NEON_PW }}
        run: |
          Rscript pipeline_indicadores.R

